// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA56egt62A6k1MNperkRom6pjhOl2Yo4yg',
    appId: '1:754610694526:web:650c025d3e33775ae6ab2f',
    messagingSenderId: '754610694526',
    projectId: 'smartlock1-a8e52',
    authDomain: 'smartlock1-a8e52.firebaseapp.com',
    storageBucket: 'smartlock1-a8e52.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoDxrXgxCfwWNuF_KbthmSWLKTJ9gvEfA',
    appId: '1:754610694526:android:41d6e4e54a9a9834e6ab2f',
    messagingSenderId: '754610694526',
    projectId: 'smartlock1-a8e52',
    storageBucket: 'smartlock1-a8e52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgij6YwSJIszaA2fbeE8wqQNlrpFHZp5g',
    appId: '1:754610694526:ios:0adb5c0b68d058c5e6ab2f',
    messagingSenderId: '754610694526',
    projectId: 'smartlock1-a8e52',
    storageBucket: 'smartlock1-a8e52.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthTutorial5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgij6YwSJIszaA2fbeE8wqQNlrpFHZp5g',
    appId: '1:754610694526:ios:0adb5c0b68d058c5e6ab2f',
    messagingSenderId: '754610694526',
    projectId: 'smartlock1-a8e52',
    storageBucket: 'smartlock1-a8e52.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthTutorial5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA56egt62A6k1MNperkRom6pjhOl2Yo4yg',
    appId: '1:754610694526:web:c7e598448c7a5615e6ab2f',
    messagingSenderId: '754610694526',
    projectId: 'smartlock1-a8e52',
    authDomain: 'smartlock1-a8e52.firebaseapp.com',
    storageBucket: 'smartlock1-a8e52.firebasestorage.app',
  );

}